# Generated by Django 2.1.7 on 2019-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_auto_20190419_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationalgorithm',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parameterizationalgorithm',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
